NAVIGATION_TOPIC = "/cmd_vel"
ACTUAL_TRAJECTORY_TOPIC = "/robot_trajectory"
COMMAND_TOPIC = "/enhanced_cmd_vel"

WORLD = "/world"
BASE_LINK = "/base_link"

# STATES :
ROLL_STATES = 10
PITCH_STATES = 10

LINEAR_VEL_STATES = 5
ANGULAR_VEL_STATES = 5

STATES = [ROLL_STATES,PITCH_STATES,LINEAR_VEL_STATES,ANGULAR_VEL_STATES]

# LIMITS [format = (low,high)]
ROLL_LIMITS = (-0.28,0.28)  # input in rads
PITCH_LIMITS = (-0.28,0.28)  # input in rads

LINEAR_VEL_LIMITS = (-0.3,0.3)   # in m/s
ANGULAR_VEL_LIMITS = (-0.4,0.4)  # in rad/s

LIMITS = [ROLL_LIMITS,PITCH_LIMITS,LINEAR_VEL_LIMITS,ANGULAR_VEL_LIMITS]

# ACTIONS:
ACTIONS = 10
